/**
 * Shared metadata / info block.
 *
 * Renders a compact set of key/value lines (e.g. address, PAN/VAT, generated by)
 * right after the header. Keeps report preamble consistent.
 */

import jsPDF from 'jspdf'
import { PDF_COLORS, PDF_FONT, PDF_SPACING } from '@/lib/pdf/theme'
import { safeText } from '@/lib/pdf/fonts'

export interface InfoLine {
  label: string
  value: string
}

export interface PdfMetadataOptions {
  startY: number
  lines: InfoLine[]
  columnCount?: number
}

/**
 * Draw metadata lines in a vertical stack (label: value on separate lines when
 * columnCount is 1, otherwise laid out in columns).
 * Returns the new y below the block.
 */
export function drawMetadata(doc: jsPDF, opts: PdfMetadataOptions): number {
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = PDF_SPACING.pageMargin
  const columnCount = opts.columnCount ?? 1
  const usable = pageWidth - margin * 2
  const colWidth = usable / columnCount
  const gap = 6

  const lines = opts.lines.filter((l) => safeText(l.value) !== '-')

  let y = opts.startY
  lines.forEach((line, idx) => {
    const col = idx % columnCount
    const row = Math.floor(idx / columnCount)
    const x = margin + col * colWidth + (col > 0 ? gap : 0)
    const lineY = opts.startY + row * 5

    doc.setFont(PDF_FONT.base, 'bold')
    doc.setFontSize(8)
    doc.setTextColor(PDF_COLORS.ink700[0], PDF_COLORS.ink700[1], PDF_COLORS.ink700[2])
    doc.text(`${safeText(line.label)}: `, x, lineY)

    doc.setFont(PDF_FONT.base, 'normal')
    doc.setTextColor(PDF_COLORS.ink900[0], PDF_COLORS.ink900[1], PDF_COLORS.ink900[2])
    const labelWidth = doc.getTextWidth(`${safeText(line.label)}: `)
    doc.text(safeText(line.value), x + labelWidth, lineY)

    y = lineY
  })

  return Math.max(opts.startY, y) + 4
}
